---
title: "Dataset & Exploration"
author: "Jie Yu"
date: 2019-03-26
output: html_document
---

```{r setup, include = TRUE, message = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = F,
  warning = F
  ) 

library(tidyverse)
library(readxl)
library(stringr)
```

### Generate resulting dataset

First, make a catalogue

```{r}
catalogue =  read_excel("./data/CHSI_DataSet.xlsx", sheet = "DATAELEMENTDESCRIPTION") %>% 
  janitor::clean_names() %>%
  # pick out "County data"
  mutate(county_data = ifelse(str_detect(.$description, c("[Cc]ounty data")) == TRUE, 1, 0)) %>% 
  filter(county_data == 1) %>% 
  # select the categories of variables which we want to use
  filter(page_name %in% c("Demographics", "SummaryMeasuresOfHealth", "RiskFactorsAndAccessToCare", "VunerablePopsAndEnvHealth")) %>% 
  filter(
    !str_detect(column_name, c("^Ecol")),
    !str_detect(column_name, c("^Salm")),
    !str_detect(column_name, c("^Shig")),
    !str_detect(column_name, c("^Toxic"))
  )
```

Select variables from different datasets based on our catalogue

```{r warning = FALSE, message = FALSE}
demographics = read.csv("./data/Demographics.csv")

# select columns from the dataframe based on variables from another dataframe
tbl_1 = read.csv("./data/Demographics.csv") %>% 
  select(one_of(dput(as.character(catalogue$column_name))))

tbl_2 = read.csv("./data/SummaryMeasuresOfHealth.csv") %>% 
  select(one_of(dput(as.character(catalogue$column_name))))

tbl_3 = read.csv("./data/RiskFactorsAndAccessToCare.csv") %>% 
  select(one_of(dput(as.character(catalogue$column_name))))

tbl_4 = read.csv("./data/VunerablePopsAndEnvHealth.csv") %>% 
  select(one_of(dput(as.character(catalogue$column_name))))

data = cbind(tbl_1, tbl_2, tbl_3, tbl_4)

# add identifiers
data = cbind(demographics$CHSI_County_Name, demographics$CHSI_State_Abbr, data) %>% 
  rename(county_name = 'demographics$CHSI_County_Name',
         state_abbr = 'demographics$CHSI_State_Abbr') %>% 
  janitor::clean_names() %>% 
  # Take out the response 'ale'
  select(ale, everything())
```

Look at our resulting dataset:

```{r}
names(data)

skimr::skim(data)
```

```{r eval = F}
write.csv(data, file = "./data/data.csv")
```


