---
title: "NK Models PCA PLS GAM"
author: "Noah Kreski"
date: "March 31, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(caret)
library(splines)
library(mgcv)
library(tidyverse)
library(ggplot2)
library(readr)
library(pls)
# import data
data = read_csv("./data/dataset.final.csv") %>% 
  select(-X1, -county_name, -state_abbr)

set.seed(3)
trRows <- createDataPartition(data$ale,
                              p = .75,
                              list = F)


data[2,34] = NA
x <- model.matrix(ale~., data)[,-1]
x = x[match(rownames(data), rownames(x)),]

n = dim(data)[2]
for (i in 2 : n){
  x[,names(data)[i]] = data[[i]]
}
rownames(x) = rownames(data)

y <- data$ale


#Train data
x1<-as.matrix(x)[trRows,]
y1<-data$ale[trRows]

#Test data
x2<-as.matrix(x)[-trRows,]
y2<-data$ale[-trRows]
```
```{r PCR}
#PCR Model
set.seed(3)
ctrl1 <- trainControl(method = "repeatedcv", number = 10, repeats = 5)
pcr.fit <- train(x1, y1,
                     method = "pcr",
                     tuneLength = 33,
                   preProcess = c( "center", "scale", "knnImpute"),
                     trControl = ctrl1)


trans = preProcess(x1, method = c("center", "scale", "knnImpute"))



predy2.pcr = predict(pcr.fit$finalModel, newdata = predict(trans, x2), ncomp = pcr.fit$bestTune$ncomp)
# test MSE
mean((predy2.pcr - y2)^2)
ggplot(pcr.fit, highlight = TRUE)+ theme_bw()
```
```{r pls}
set.seed(3)
ctrl1 <- trainControl(method = "repeatedcv", number = 10, repeats = 5)
pls.fit <- train(x1, y1,
                     method = "pls",
                     tuneLength = 33,
                   preProcess = c( "center", "scale", "knnImpute"),
                     trControl = ctrl1)


trans = preProcess(x1, method = c("center", "scale", "knnImpute"))


predy2.pls = predict(pls.fit$finalModel, newdata = predict(trans, x2), ncomp = pls.fit$bestTune$ncomp)
# test MSE
mean((predy2.pls - y2)^2)
ggplot(pls.fit, highlight = TRUE)+ theme_bw()
```
```{r}
set.seed(3)
resamp <- resamples(list(pcr = pcr.fit, 
                         pls = pls.fit))
summary(resamp)
bwplot(resamp, metric = "RMSE")
```
```{r gam}
#set.seed(3)
#ctrl1 <- trainControl(method = "cv", number = 5)
#gam.fit <- train(x, y,
#                     method = "gam",
#                    tuneLength = data.frame(method = "GCV.Cp", select = c("TRUE", "FALSE")),
#                   preProcess = c( "center", "scale", "knnImpute"),
#                     trControl = ctrl1)
#summary(gam.fit)
#plot(gam.fit$finalModel)
```