---
title: "Unsupervised"
author: Shuwei Liu
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = F,
  warning = F
  ) 

library(tidyverse)
library(glmnet)
library(plotmo)
library(caret)
library(ISLR)
library(factoextra)
library(gridExtra)
library(corrplot)
library(RColorBrewer) 
library(gplots)
```

```{r}
data = read_csv("./data/dataset.final.csv") %>% 
  select(-X1, -county_name) %>% 
  select(state_abbr, everything()) %>% 
  na.omit() %>% 
  group_by(state_abbr) %>% 
  summarise_all(funs(mean))

state <- data.frame(state_abbr = state.abb,
                    state_name = state.name)

data = left_join(data, state, by = "state_abbr") %>% 
  select(state_abbr, state_name, ale, everything()) %>% 
  # state_name is factor
  mutate(state_name = as.character(state_name)) 

data$state_name[is.na(data$state_name)] <- "District of Columbia"


dat1 <- data[,3:36]
dat1 <- scale(dat1) # scaled
rownames(dat1) <- data$state_name
```

```{r}
col1 <- colorRampPalette(brewer.pal(9, "GnBu"))(100)
col2 <- colorRampPalette(brewer.pal(3, "Spectral"))(2)

heatmap.2(t(dat1), 
          col = col1, keysize=.8, key.par = list(cex=.5),
          trace = "none", key = TRUE, cexCol = 0.75, 
          labCol = as.character(data$state_abbr),
          margins = c(10, 10))
```


```{r}
hc.complete <- hclust(dist(dat1), method = "complete")
```

```{r}
fviz_dend(hc.complete, k = 5,        
          cex = 0.5, 
          palette = "jco", 
          color_labels_by_k = TRUE,
          rect = TRUE, rect_fill = TRUE, rect_border = "jco")

ind.complete <- cutree(hc.complete, 5)

# states belong to cluster 1:
dat1[ind.complete == 1,] %>% rownames() 

# states belong to cluster 2:
dat1[ind.complete == 2,] %>% rownames()

# states belong to cluster 3:
dat1[ind.complete == 3,] %>% rownames()

# states belong to cluster 4:
dat1[ind.complete == 4,] %>% rownames()

# states belong to cluster 5:
dat1[ind.complete == 5,] %>% rownames()
```

