---
title: "Lasso & Ridge"
author: Shuwei Liu
date: 3/31/2019
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(glmnet)
library(plotmo)
library(caret)
library(RANN)
```

```{r}
# import data
data = read_csv("./data/dataset.final.csv") %>% 
  select(-X1, -county_name, -state_abbr)

set.seed(3)
trRows <- createDataPartition(data$ale,
                              p = .75,
                              list = F)


data[2,34] = NA
x <- model.matrix(ale~., data)[,-1]
x = x[match(rownames(data), rownames(x)),]

n = dim(data)[2]
for (i in 2 : n){
  x[,names(data)[i]] = data[[i]]
}
rownames(x) = rownames(data)

y <- data$ale


#Train data
x1<-as.matrix(x)[trRows,]
y1<-data$ale[trRows]

#Test data
x2<-as.matrix(x)[-trRows,]
y2<-data$ale[-trRows]
```


## `caret`

### Ridge

```{r}
set.seed(3)
ctrl1 <- trainControl(method = "repeatedcv", number = 10, repeats = 5)
ridge.fit <- train(x1, y1,
                     method = "glmnet",
                     tuneGrid = expand.grid(alpha = 0,  
                                            lambda = exp(seq(-5, 2, length=200))),
                   preProcess = c( "center", "scale", "knnImpute"),
                     trControl = ctrl1)

plot(ridge.fit, xTrans = function(x1) log(x1)) 

trans = preProcess(x1, method = c("center", "scale", "knnImpute"))

ridge.fit$bestTune

coef_ridge = coef(ridge.fit$finalModel,ridge.fit$bestTune$lambda)
head(coef_ridge)

pred_rg = predict(ridge.fit$finalModel, s = ridge.fit$bestTune$lambda, newx = predict(trans, x2),
                  type = "response")
# test MSE
mean((pred_rg - y2)^2)
```

### Lasso

```{r}
set.seed(3)
lasso.fit <- train(x1, y1,
                   method = "glmnet",
                   tuneGrid = expand.grid(alpha = 1, 
                                          lambda = exp(seq(-4, -1, length=200))),
                   preProcess = c("center", "scale", "knnImpute"),
                   trControl = ctrl1)

plot(lasso.fit, xTrans = function(x1) log(x1))

trans = preProcess(x1, method = c("center", "scale", "knnImpute"))

coef_lasso = 
  predict(lasso.fit$finalModel, newx =  predict(trans,x2), 
                        s = lasso.fit$bestTune$lambda, type="coefficients")

nrow(summary(coef_lasso))
# There are 17 non-zero coefficient estimates

predy2.lasso <- predict(lasso.fit$finalModel, newx = predict(trans,x2), 
                        s = lasso.fit$bestTune$lambda, type = "response")
# test MSE
mean((predy2.lasso - y2)^2)
```

```{r}
set.seed(3)

lm.fit <- train(x1, y1,
                method = "lm",
                preProcess = c("center", "scale", "knnImpute"),
                trControl = ctrl1)

resamp <- resamples(list(lasso = lasso.fit, 
                         ridge = ridge.fit, 
                         lm = lm.fit))
summary(resamp)
```

```{r}
bwplot(resamp, metric = "RMSE")
```

